name: CI

on: [push]

jobs:
  linter:
    name: Run mypy linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mypy
      run: mypy src tests --explicit-package-bases --ignore-missing-imports

  tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    needs: [linter]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: python -m pytest tests/unit --capture=no
    
    - name: Run integration tests
      run: python -m pytest tests/integration --capture=no
  
#   docker:
#     name: Publishes to Docker Hub
#     runs-on: ubuntu-latest
#     needs: [tests]
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: gaponukz/atass-payments:latest